In [ ]:
#Punto 1

import numpy as np

def diag_store(m, init_pos=0, size=4):
    #ndim se utiliza para obtener el número de dimensiones de un array y shape compara las dimensiones
    assert m.ndim == 2 and m.shape[0] == m.shape[1], "El array no es cuadrado"  
    #np.allclose compara dos arrays, np.diag crea una matriz a partir del vector de la matriz diagonal principal que devuelve np.diagonal(m)
    assert np.allclose(m, np.diag(np.diagonal(m))), "El array no es diagonal"   
    indices = np.indices(m.shape) 
    positions = indices[0] * size + indices[1] * (size + 1) + init_pos 
    #Aquí despues del calculo hay valores que no queremos y solo nos interesan los valores de las 3 posiciones que están cada 3 valores en el array positions luego de aplanarlo
    return positions.flatten()[::3]                                             
                                                                                

a = np.array([[1,0,0], [0,3,0], [0,0,-3]])
print(a)
diag_store(a, init_pos=19, size=5)

[[ 1  0  0]
 [ 0  3  0]
 [ 0  0 -3]]


array([19, 24, 29])

In [ ]:
#Punto 2

import numpy as np

def triang_store(m, init_pos=0, size=4, orientation="columns"):
    assert m.ndim == 2 and m.shape[0] == m.shape[1], "El array no es cuadrado"
    assert np.all(np.triu(m) == m), "El array no es triangular superior" #np.triu devuelve una matriz triangular con el valor que se le pasa y luego los comparamos
    assert orientation == "columns" or orientation == "rows", "El parámetro 'orientation' debe ser 'columns' o 'rows'"

    positions = []
    if orientation == "columns":
        for j in range(m.shape[1]):
            for i in range(j, m.shape[0]+(j+1)):
                  positions.append(init_pos + (size*i))
    else:
        for i in range(m.shape[0]):
            for j in range(i, m.shape[1]+(i+1)):
                positions.append(init_pos + (size*j))
    return np.unique(positions)

a = np.array([[1, 0, 3], [0, 3, 1], [0, 0, -3]])
#a = np.array([[1,0,0], [0,3,0], [0,0,-3]])
print(a)
print(triang_store(a, init_pos=19, size=5))


[[ 1  0  3]
 [ 0  3  1]
 [ 0  0 -3]]
[19 24 29 34 39 44]


In [ ]:
#Punto 3

import pandas as pd
import numpy as np
import itertools  

def get_storage_positions(dims, order, size, init_pos=0):
    assert len(dims) == len(order), "Las dimensiones y el orden deben tener la misma longitud"

    #Generar todas las posibles coordenadas de la matriz
    coordinates = np.array(list(itertools.product(*[range(dim) for dim in dims])))

    #Crear un DataFrame con las coordenadas y ordenar según el orden de almacenamiento
    df = pd.DataFrame(coordinates, columns=order)
    df.sort_values(by=order, inplace=True)

    #Generar una matriz de ceros con las dimensiones especificadas
    storage_positions = np.zeros(dims, dtype=int)

    #Recorrer el DataFrame y actualizar las coordenadas en la matriz de posiciones
    for idx, row in df.iterrows():
        storage_positions[tuple(row.values)] = init_pos

        #Incrementar la posición inicial para el siguiente elemento
        init_pos += size

    return storage_positions

print(get_storage_positions(dims = [3,2], order = [0,1], size=4))
print("--")
print(get_storage_positions(dims = [2,3,4], order = [0,1,2], size=4))
print("--")
print(get_storage_positions(dims = [2,3,4], order = [2,1,0], size=4))
print("--")
print(get_storage_positions(dims = [2,2,2], order = [0,1,2], size=4))
print("--")
print(get_storage_positions(dims = [2,2,2], order = [2,1,0], size=4))

[[ 0  4]
 [ 8 12]
 [16 20]]
--
[[[ 0  4  8 12]
  [16 20 24 28]
  [32 36 40 44]]

 [[48 52 56 60]
  [64 68 72 76]
  [80 84 88 92]]]
--
[[[ 0  4  8 12]
  [16 20 24 28]
  [32 36 40 44]]

 [[48 52 56 60]
  [64 68 72 76]
  [80 84 88 92]]]
--
[[[ 0  4]
  [ 8 12]]

 [[16 20]
  [24 28]]]
--
[[[ 0  4]
  [ 8 12]]

 [[16 20]
  [24 28]]]


In [23]:
#Punto 4

import numpy as np

def get_storage_order(r):
    assert isinstance(r, np.ndarray), "La entrada debe ser un array de NumPy"
    assert r.ndim > 1, "El array debe tener al menos 2 dimensiones"

    dimensions = len(r.shape)
    storage_order = []

    for i in range(dimensions):
        #Generar una lista de slices equivalentes a la notación de indexado
        slices = [slice(None)] * dimensions
        slices[i] = slice(2)

        #Obtener los dos primeros elementos en el eje i
        first_two = r[tuple(slices)]

        #Calcular la diferencia entre los dos primeros elementos
        diff = np.diff(first_two.ravel())

        #Encontrar el índice del eje que tiene la mayor diferencia absoluta
        order = np.argmax(np.abs(diff))

        #Agregar el eje ordenado a la lista de orden de almacenamiento
        storage_order.append(order)

    # Ordenar los ejes de acuerdo al orden de almacenamiento
    sorted_order = np.argsort(storage_order)

    return tuple(sorted_order)









r1 = np.array([[[ 0, 4, 8, 12],
  [16, 20, 24, 28],
  [32, 36, 40, 44]],

 [[48, 52, 56, 60],
  [64, 68, 72, 76],
  [80, 84, 88, 92]]])

r2 = np.array([[[0, 4, 8, 12]
, [32, 36, 40, 44]
, [64, 68, 72, 76]]

, [[16, 20, 24, 28]
, [48, 52, 56, 60]
, [80, 84, 88, 92]]])

print(get_storage_order(r1))
print(get_storage_order(r2))


(0, 2, 1)
(2, 1, 0)
