In [8]:
#Punto 1

def add_to_dict(d, key1, key2, val):
    if key1 not in d.keys():
      d[key1] = {}
    d[key1][key2] = val
    return d
    
d = {}
add_to_dict(d, 10, 3,  "20")
add_to_dict(d, 1, 5,  "4")
add_to_dict(d, 1, 2, "14")
print(d)
print (d[1][5])

{10: {3: '20'}, 1: {5: '4', 2: '14'}}
4


In [13]:
#Punto 2
import itertools
import numpy as np

def SparseMatrix2(m=None, **kwargs):

    def add_to_dict(d, key1, key2, val):
      if key1 not in d.keys():
        d[key1] = {}
      d[key1][key2] = val
      return d

    class SparseMatrix2_class:

        def __init__(self, m=m, **kwargs):
            self.rows = {}
            self.shape =  (0, 0) if m is None else (len(m), len(m[0]))

            if m is not None:
                for i, row in enumerate(m):
                    for j, val in enumerate(row):
                        if val != 0:
                            add_to_dict(self.rows, i, j, val)

        def sparseness_metric(self):
            metric = self.shape[0] * self.shape[1]
            non_zero_elements = sum(len(row) for row in self.rows.values())
            sparseness = 1 - (non_zero_elements / metric)
            return sparseness
    
    return SparseMatrix2_class(**kwargs)

def random_sparse_matrix(size):
    m = np.random.randint(2, size=size)
    m = m * np.random.randint(10,size=size)
    return m

m = random_sparse_matrix((5,3))

sm = SparseMatrix2(m)
print(m.shape, sm.sparseness_metric())

s = SparseMatrix2(m)
print("rows", s.rows)
print("length of each row", [len(s.rows[i]) for i in list(s.rows.keys())])

s = SparseMatrix2(None)
s.shape

(5, 3) 0.6
rows {0: {2: 1}, 1: {1: 9}, 2: {0: 1}, 3: {1: 1}, 4: {1: 6, 2: 8}}
length of each row [1, 1, 1, 1, 2]


(0, 0)

In [14]:
#Punto 3

def SparseMatrix3(m=None, **kwargs):
    import itertools
    import numpy as np

    def add_to_dict(d, key1, key2, val):
        if key1 not in d.keys():
            d[key1] = {}
        d[key1][key2] = val
        return d

    class SparseMatrix3_class:
        def __init__(self, m=m, **kwargs):
            self.rows = {}
            self.shape = (0, 0) if m is None else (len(m), len(m[0]))

            if m is not None:
                for i, row in enumerate(m):
                    for j, val in enumerate(row):
                        if val != 0:
                            add_to_dict(self.rows, i, j, val)

        def to_dense(self):
            r = np.zeros(self.shape)
            for i, row in self.rows.items():
                for j, val in row.items():
                    r[i, j] = val
            return r

        def T(self):
            r = self.__class__(m=None)
            for i, row in self.rows.items():
                for j, val in row.items():
                    add_to_dict(r.rows, j, i, val)
            r.shape = (self.shape[1], self.shape[0])
            return r

    return SparseMatrix3_class(**kwargs)

def random_sparse_matrix(size):
    m = np.random.randint(2, size=size)
    m = m * np.random.randint(10,size=size)
    return m

m = random_sparse_matrix((5,3))
s = SparseMatrix3(m)

print(m)


[[0 0 7]
 [3 0 1]
 [0 9 0]
 [0 0 0]
 [3 0 1]]


In [15]:
#Punto 4

def SparseMatrix4(m=None, **kwargs):
    import itertools

    def add_to_dict(d, key1, key2, val):
        if key1 not in d.keys():
            d[key1] = {}
        d[key1][key2] = val
        return d

    class SparseMatrix4_class:
        def __init__(self, m=m, **kwargs):
            self.rows = {}
            self.shape = (0, 0) if m is None else (len(m), len(m[0]))

            if m is not None:
                for i, row in enumerate(m):
                    for j, val in enumerate(row):
                        if val != 0:
                            add_to_dict(self.rows, i, j, val)

        def __getitem__(self, pos):
            i, j = pos
            assert 0 <= i < self.shape[0] and 0 <= j < self.shape[1], "Index out of range"
            if i in self.rows and j in self.rows[i]:
                return self.rows[i][j]
            else:
                return 0

    return SparseMatrix4_class(**kwargs)

def random_sparse_matrix(size):
    m = np.random.randint(2, size=size)
    m = m * np.random.randint(10,size=size)
    return m

m = random_sparse_matrix((5,3))

print("original matrix shape", m.shape)
print(m)

import itertools

s = SparseMatrix4(m)

print("inner dict", s.rows)
print("\ncoord   value_in_m       value_in_s")
for i,j in itertools.product(list(range(m.shape[0])), list(range(m.shape[1]))):                
    print("(%d,%d)   %5d        %5d"%(i,j, m[i,j], s[i,j]))


original matrix shape (5, 3)
[[3 6 4]
 [8 6 0]
 [6 0 0]
 [1 0 0]
 [0 0 0]]
inner dict {0: {0: 3, 1: 6, 2: 4}, 1: {0: 8, 1: 6}, 2: {0: 6}, 3: {0: 1}}

coord   value_in_m       value_in_s
(0,0)       3            3
(0,1)       6            6
(0,2)       4            4
(1,0)       8            8
(1,1)       6            6
(1,2)       0            0
(2,0)       6            6
(2,1)       0            0
(2,2)       0            0
(3,0)       1            1
(3,1)       0            0
(3,2)       0            0
(4,0)       0            0
(4,1)       0            0
(4,2)       0            0
